[package]
name = "lambda-sparkling-water-0b10"
version = "0.1.0"
edition = "2021"

[dependencies]
glass_pumpkin = "1.7.0"
modinverse = "0.1.1"
num-bigint = "0.4.5"
num-integer = "0.1.46"
num-traits = "0.2.19"
rand = "0.8.5"
sha2 = "0.10.8"
